# Use the official PostgreSQL image (tracks your script's behavior)
FROM postgres:16-bookworm


# Copy the initialization SQL script into the automated entrypoint folder
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432
